Repository nextcloud/files_pdfviewer, pull requests merged in 2018-10, with the labels that each got.

#100 Remove unneeded CSS rule for IE 11
  css/style.css
Labels: 3. to review, backport-request, bug, design

#101 [stable14] Remove unneeded CSS rule for IE 11
  css/style.css
Labels: 3. to review

#99 Hide footer in public share page
  css/style.css
Labels: 3. to review, backport-request, bug, design, regression

#103 [stable14] Hide footer in public share page
  css/style.css
Labels: 3. to review
