Repository nextcloud/files_pdfviewer, pull requests merged in 2020-08, with the labels that each got.

#196 Allow pdfviewer to open illustrator (.ai) files
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/main.js
Labels: 4. to release, enhancement

#200 Update README.md
  README.md
Labels: 3. to review, enhancement

#197 update readme and appinfo to feature .ai files
  README.md
  appinfo/info.xml
Labels: 3. to review, enhancement

#205 focus the pdfviewer iframe directly after opening
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
Labels: 4. to release, enhancement

#206 Fix can download check
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  src/utils/canDownload.js
Labels: 3. to review, bug
