Repository nextcloud/files_pdfviewer, pull requests merged in 2021-08, with the labels that each got.

#457 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#459 Fix hide download and printing
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.LICENSE.txt
  js/files_pdfviewer-workersrc.js.map
  src/public.js
  src/utils/canDownload.js
  src/utils/isSecureViewerAvailable.js
  src/workersrc.js
Labels: bug, 3. to review, backport-request, regression

#461 [stable20] Fix hide download and printing
  .github/workflows/phpunit.yml
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.LICENSE.txt
  js/files_pdfviewer-workersrc.js.map
  src/public.js
  src/utils/canDownload.js
  src/utils/isSecureViewerAvailable.js
  src/workersrc.js
Labels: bug, 3. to review, regression

#462 [stable21] Fix hide download and printing
  .github/workflows/phpunit.yml
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.LICENSE.txt
  js/files_pdfviewer-workersrc.js.map
  src/public.js
  src/utils/canDownload.js
  src/utils/isSecureViewerAvailable.js
  src/workersrc.js
Labels: bug, 3. to review, regression

#463 Fix body footer hiding
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  src/public.js
Labels: bug, design, 3. to review, backport-request

#467 Disable download for pdf files
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  src/public.js
Labels: bug, 3. to review, regression

#468 Remove images for dark mode
  js/pdfjs/web/images/findbarButton-next-dark.svg
  js/pdfjs/web/images/findbarButton-previous-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-documentProperties-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-firstPage-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-handTool-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-lastPage-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-rotateCcw-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-rotateCw-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-scrollHorizontal-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-scrollVertical-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-scrollWrapped-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-selectTool-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-spreadEven-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-spreadNone-dark.svg
  js/pdfjs/web/images/secondaryToolbarButton-spreadOdd-dark.svg
  js/pdfjs/web/images/toolbarButton-bookmark-dark.svg
  js/pdfjs/web/images/toolbarButton-download-dark.svg
  js/pdfjs/web/images/toolbarButton-menuArrow-dark.svg
  js/pdfjs/web/images/toolbarButton-openFile-dark.svg
  js/pdfjs/web/images/toolbarButton-pageDown-dark.svg
  js/pdfjs/web/images/toolbarButton-pageUp-dark.svg
  js/pdfjs/web/images/toolbarButton-presentationMode-dark.svg
  js/pdfjs/web/images/toolbarButton-print-dark.svg
  js/pdfjs/web/images/toolbarButton-search-dark.svg
  js/pdfjs/web/images/toolbarButton-secondaryToolbarToggle-dark.svg
  js/pdfjs/web/images/toolbarButton-sidebarToggle-dark.svg
  js/pdfjs/web/images/toolbarButton-viewAttachments-dark.svg
  js/pdfjs/web/images/toolbarButton-viewLayers-dark.svg
  js/pdfjs/web/images/toolbarButton-viewOutline-dark.svg
  js/pdfjs/web/images/toolbarButton-viewThumbnail-dark.svg
  js/pdfjs/web/images/toolbarButton-zoomIn-dark.svg
  js/pdfjs/web/images/toolbarButton-zoomOut-dark.svg
  js/pdfjs/web/images/treeitem-collapsed-dark.svg
  js/pdfjs/web/images/treeitem-expanded-dark.svg
Labels: 3. to review, technical debt

#472 Fix download & print view
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  src/public.js
  src/views/PDFView.vue
  src/workersrc.js
Labels: bug, 3. to review, backport-request
