Repository nextcloud/files_pdfviewer, pull requests merged in 2022-06, with the labels that each got.

#610 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#609 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#611 Ensure the content takes the whole height when we hide the footer
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  src/public.js
Labels: bug, 3. to review, backport-request

#616 [stable24] Fix footer not hidden when Talk sidebar is shown
  css/style.css
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  src/public.js
Labels: bug, 3. to review, regression

#617 [stable23] Fix footer not hidden when Talk sidebar is shown
  css/style.css
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  src/public.js
Labels: bug, 3. to review, regression

#618 [stable22] Fix footer not hidden when Talk sidebar is not shown
  css/style.css
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  src/public.js
Labels: bug, 3. to review, regression

#619 Fix pdfJs template
  templates/viewer.php
Labels: bug, 3. to review
