Repository nextcloud/files_pdfviewer, pull requests merged in 2022-05, with the labels that each got.

#596 Adapt layout after viewer update
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
Labels: bug, 3. to review, backport-request

#598 Update phpunit workflows
  .github/workflows/oci.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  tests/phpunit.xml
Labels: 4. to release, backport-request

#600 [stable23] Update phpunit workflows
  .github/workflows/oci.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  tests/phpunit.xml
Labels: 4. to release, backport-request

#595 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#581 Replace deprecated String.prototype.substr()
  pdfjs-get.js
Labels: 3. to review, technical debt

#604 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
