Repository nextcloud/files_pdfviewer, pull requests merged in 2022-01, with the labels that each got.

#530 Bump actions
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
Labels: 4. to release, backport-request

#532 [stable21] Bump actions
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
  .github/workflows/oci.yml
  package-lock.json
  package.json
Labels: 4. to release, backport-request

#543 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#548 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: backport-request, dependencies

#555 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
