Repository nextcloud/files_pdfviewer, pull requests merged in 2023-08, with the labels that each got.

#791 feat: Fix styling for version comparison
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/main.js
  src/views/PDFView.vue
Labels: enhancement, 3. to review

#793 [stable26] Replace deprecated "request" with "axios"
  package-lock.json
  package.json
  pdfjs-get.js
Labels: bug, 3. to review, dependencies

#794 [stable25] Replace deprecated "request" with "axios"
  package-lock.json
  package.json
  pdfjs-get.js
Labels: bug, 3. to review, dependencies

#807 [stable27] Fix extraction of PDF.js package
  js/pdfjs/web/locale/pa-IN/viewer.properties
  js/pdfjs/web/locale/pl/viewer.properties
  js/pdfjs/web/locale/pt-BR/viewer.properties
  js/pdfjs/web/locale/pt-PT/viewer.properties
  js/pdfjs/web/locale/rm/viewer.properties
  js/pdfjs/web/locale/ro/viewer.properties
  js/pdfjs/web/locale/ru/viewer.properties
  js/pdfjs/web/locale/sat/viewer.properties
  js/pdfjs/web/locale/sc/viewer.properties
  js/pdfjs/web/locale/scn/viewer.properties
  js/pdfjs/web/locale/sco/viewer.properties
  js/pdfjs/web/locale/si/viewer.properties
  js/pdfjs/web/locale/sk/viewer.properties
  js/pdfjs/web/locale/skr/viewer.properties
  js/pdfjs/web/locale/sl/viewer.properties
  js/pdfjs/web/locale/son/viewer.properties
  js/pdfjs/web/locale/sq/viewer.properties
  js/pdfjs/web/locale/sr/viewer.properties
  js/pdfjs/web/locale/sv-SE/viewer.properties
  js/pdfjs/web/locale/szl/viewer.properties
  js/pdfjs/web/locale/ta/viewer.properties
  js/pdfjs/web/locale/te/viewer.properties
  js/pdfjs/web/locale/tg/viewer.properties
  js/pdfjs/web/locale/th/viewer.properties
  js/pdfjs/web/locale/tl/viewer.properties
  js/pdfjs/web/locale/tr/viewer.properties
  js/pdfjs/web/locale/trs/viewer.properties
  js/pdfjs/web/locale/uk/viewer.properties
  js/pdfjs/web/locale/ur/viewer.properties
  js/pdfjs/web/locale/uz/viewer.properties
  js/pdfjs/web/locale/vi/viewer.properties
  js/pdfjs/web/locale/wo/viewer.properties
  js/pdfjs/web/locale/xh/viewer.properties
  js/pdfjs/web/locale/zh-CN/viewer.properties
  js/pdfjs/web/locale/zh-TW/viewer.properties
  package-lock.json
  package.json
  pdfjs-get.js
Labels: bug, 3. to review, dependencies

#808 [stable26] Fix extraction of PDF.js package
  js/pdfjs/web/locale/pa-IN/viewer.properties
  js/pdfjs/web/locale/pl/viewer.properties
  js/pdfjs/web/locale/pt-BR/viewer.properties
  js/pdfjs/web/locale/pt-PT/viewer.properties
  js/pdfjs/web/locale/rm/viewer.properties
  js/pdfjs/web/locale/ro/viewer.properties
  js/pdfjs/web/locale/ru/viewer.properties
  js/pdfjs/web/locale/sat/viewer.properties
  js/pdfjs/web/locale/sc/viewer.properties
  js/pdfjs/web/locale/scn/viewer.properties
  js/pdfjs/web/locale/sco/viewer.properties
  js/pdfjs/web/locale/si/viewer.properties
  js/pdfjs/web/locale/sk/viewer.properties
  js/pdfjs/web/locale/skr/viewer.properties
  js/pdfjs/web/locale/sl/viewer.properties
  js/pdfjs/web/locale/son/viewer.properties
  js/pdfjs/web/locale/sq/viewer.properties
  js/pdfjs/web/locale/sr/viewer.properties
  js/pdfjs/web/locale/sv-SE/viewer.properties
  js/pdfjs/web/locale/szl/viewer.properties
  js/pdfjs/web/locale/ta/viewer.properties
  js/pdfjs/web/locale/te/viewer.properties
  js/pdfjs/web/locale/tg/viewer.properties
  js/pdfjs/web/locale/th/viewer.properties
  js/pdfjs/web/locale/tl/viewer.properties
  js/pdfjs/web/locale/tr/viewer.properties
  js/pdfjs/web/locale/trs/viewer.properties
  js/pdfjs/web/locale/uk/viewer.properties
  js/pdfjs/web/locale/ur/viewer.properties
  js/pdfjs/web/locale/uz/viewer.properties
  js/pdfjs/web/locale/vi/viewer.properties
  js/pdfjs/web/locale/wo/viewer.properties
  js/pdfjs/web/locale/xh/viewer.properties
  js/pdfjs/web/locale/zh-CN/viewer.properties
  js/pdfjs/web/locale/zh-TW/viewer.properties
  package-lock.json
  package.json
  pdfjs-get.js
Labels: bug, 3. to review, dependencies

#809 [stable25] Fix extraction of PDF.js package
  package-lock.json
  package.json
  pdfjs-get.js
Labels: bug, 3. to review, dependencies

#810 add workflow to notify of changed viewer.html
  .github/workflows/check-viewer.yml
Labels: enhancement, 3. to review

#798 Fix initialization after bump to PDF.js 3.9.179
  templates/viewer.php
Labels: bug, 3. to review, regression
