Repository nextcloud/files_pdfviewer, pull requests merged in 2023-07, with the labels that each got.

#768 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#764 [stable27] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.LICENSE.txt
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  package-lock.json
Labels: 3. to review, dependencies

#763 [stable24] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.LICENSE.txt
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js.LICENSE.txt
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js.map
  package-lock.json
  src/main.js
  src/public.js
  src/services/logger.js
  src/utils/canDownload.js
  src/utils/isPdf.js
  src/utils/isPublicPage.js
  src/utils/isSecureViewerAvailable.js
  src/utils/redirectIfNotIframe.js
  src/views/PDFView.vue
  src/workersrc.js
Labels: 4. to release, dependencies

#766 [stable26] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.LICENSE.txt
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.LICENSE.txt
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  package-lock.json
  src/main.js
  src/public.js
  src/services/logger.js
  src/utils/canDownload.js
  src/utils/isPdf.js
  src/utils/isPublicPage.js
  src/utils/isSecureViewerAvailable.js
  src/utils/redirectIfNotIframe.js
  src/views/PDFView.vue
  src/workersrc.js
Labels: 4. to release, dependencies

#772 [stable27] Fix npm audit (again)
  package-lock.json
Labels: 3. to review, dependencies

#773 [stable26] Fix npm audit (again)
  package-lock.json
Labels: 3. to review, dependencies

#774 [stable25] Fix npm audit (again)
  package-lock.json
Labels: 3. to review, dependencies

#780 [stable24] Update phpunit workflows from master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  composer.json
Labels: 3. to review

#779 [stable25] Update phpunit workflows from master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  composer.json
Labels: 3. to review

#778 [stable26] Update phpunit workflows from master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
Labels: 3. to review

#777 [stable27] Update phpunit workflows from master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
Labels: 3. to review

#775 [stable24] Fix npm audit (again)
  package-lock.json
Labels: 3. to review, dependencies

#788 allow to resize sidebar
  templates/viewer.php
Labels: enhancement, 3. to review
