Repository nextcloud/files_pdfviewer, pull requests merged in 2023-04, with the labels that each got.

#728 chore(maintainers): Update CODEOWNERS file
  .github/CODEOWNERS
Labels: 3. to review

#731 add npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#735 update npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: bug, 3. to review

#740 Replace deprecated "request" with "axios"
  package-lock.json
  package.json
  pdfjs-get.js
Labels: bug, 3. to review, dependencies

#739 [stable26] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  package-lock.json
Labels: 3. to review, dependencies

#737 [stable25] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  package-lock.json
Labels: 3. to review, dependencies

#738 [stable24] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  package-lock.json
Labels: 3. to review, dependencies
