Repository nextcloud/files_pdfviewer, pull requests merged in 2023-11, with the labels that each got.

#845 fix pdf-viewer sizing
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
Labels: bug, 3. to review

#842 Setup Transifex translations
  .l10nignore
  .tx/backport
  .tx/config
  l10n/.gitkeep
Labels: 3. to review

#850 Show forms as read-only if the file is not editable
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
Labels: bug, 3. to review

#857 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#859 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
