Repository nextcloud/files_pdfviewer, pull requests merged in 2024-07, with the labels that each got.

#991 Fix missing/incorrect SPDX data
  .reuse/dep5
  LICENSES/CC0-1.0.txt
Labels: 4. to release

#992 Migrate REUSE file to toml
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#993 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#996 chore: update workflows from templates
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 3. to review, dependencies, automated
