Repository nextcloud/files_pdfviewer, pull requests merged in 2024-12, with the labels that each got.

#1077 Show error when trying to open a shared PDF without download permissions
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  src/public.js
  src/utils/hideDownload.js
  src/utils/isSecureViewerAvailable.js
  src/views/PDFView.vue
  src/workersrc.js
Labels: bug, 3. to review, backport-request

#1099 fix: update nextcloud/coding-standard to 1.3
  composer.json
  composer.lock
  tests/Unit/Controller/DisplayControllerTest.php
  tests/bootstrap.php
Labels: 3. to review

#1086 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
