Repository nextcloud/files_pdfviewer, pull requests merged in 2024-08, with the labels that each got.

#1002 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1009 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1010 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1011 feat(deps): Add Nextcloud 31 support on master
  .github/dependabot.yml
  .github/workflows/npm-audit-fix.yml
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1019 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#998 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#939 Update viewer.css
  js/pdfjs/web/viewer.css
Labels: feedback-requested

#1023 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#1033 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1031 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1032 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1025 chore: Add psalm for PHP static code analysis
  .github/workflows/psalm.yml
  .gitignore
  REUSE.toml
  composer.json
  composer.lock
  lib/Listeners/CSPListener.php
  lib/Listeners/LoadPublicViewerListener.php
  lib/Listeners/LoadViewerListener.php
  psalm.xml
  tests/stubs/oca_viewer_event_loadviewer.php
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: enhancement, 3. to review
