Repository nextcloud/files_pdfviewer, pull requests merged in 2024-06, with the labels that each got.

#973 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#974 chore(CI): Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#984 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#983 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#982 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#987 Update PDF icon(s) to latest server-version used one
  img/app.png
  img/app.svg
  img/toolbarButton-secondaryToolbarClose.svg
  img/toolbarButton-secondaryToolbarSave.svg
Labels: 4. to release
