Repository nextcloud/files_pdfviewer, pull requests merged in 2025-01, with the labels that each got.

#1109 CI: Update workflows + remove broken ones
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
Labels: bug, 3. to review, backport-request

#1112 fix(composer): fix running composer with `--no-dev` option
  composer.json
Labels: bug, 3. to review, backport-request

#1106 Fix path to image resources
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.map
  src/workersrc.js
  templates/viewer.php
Labels: bug, 3. to review, backport-request

#1111 [stable29] CI: Update workflows + remove broken ones
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#1105 [stable29] Update php-cs-fixer to a PHP 8.3 compatible version
  composer.lock
  tests/Unit/Controller/DisplayControllerTest.php
  tests/bootstrap.php
Labels: bug, 3. to review, dependencies

#1104 [stable30] Update php-cs-fixer to a PHP 8.3 compatible version
  composer.lock
  tests/Unit/Controller/DisplayControllerTest.php
  tests/bootstrap.php
Labels: bug, 3. to review, dependencies

#1118 ci: Update workflows from organization - fixes compile command
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: 3. to review, backport-request

#1121 chore(CI): Updating npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies

#1108 Fix disabled annotation edition in view only files
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
  templates/viewer.php
Labels: bug, 3. to review, backport-request
