Repository nextcloud/files_pdfviewer, pull requests merged in 2025-02, with the labels that each got.

#1107 Move initialization from helper script to Vue component
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-workersrc.js
  js/files_pdfviewer-workersrc.js.license
  js/files_pdfviewer-workersrc.js.map
  src/views/PDFView.vue
  src/workersrc.js
Labels: 3. to review, backport-request

#1147 chore: move the issue template into the ISSUE_TEMPLATE folder
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Bug_report.md.license
Labels: 3. to review

#1159 Get PDF.js version from "package-lock.json"
  pdfjs-get.js
Labels: bug, 3. to review, backport-request

#1163 fix: Pin pdfjs-dist to exact 4.0.189
  package-lock.json
  package.json
Labels: 3. to review, backport-request, dependencies

#1167 [stable29] fix: Pin pdfjs-dist to exact 4.0.189
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1166 [stable30] fix: Pin pdfjs-dist to exact 4.0.189
  package-lock.json
  package.json
Labels: 3. to review, dependencies
