Repository nextcloud/files_pdfviewer, pull requests merged in 2025-05, with the labels that each got.

#1201 [master] Fix npm audit
  LICENSES/BSD-2-Clause.txt
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.license
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.license
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.map.license
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.license
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.map.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js.map.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js.map.license
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.license
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.map
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.map.license
  package-lock.json
Labels: 3. to review, dependencies

#1200 [stable31] Fix npm audit
  LICENSES/BSD-2-Clause.txt
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.license
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.license
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.map.license
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.license
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.map.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js.map.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js.license
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js.map.license
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.license
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.map
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.map.license
  package-lock.json
Labels: 3. to review, dependencies

#1198 [stable29] Fix npm audit
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Cp_Wd5Qd_mjs.js.map
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js
  js/files_pdfviewer-node_modules_nextcloud_dialogs_dist_chunks_index-Ly0obkwS_mjs.js.map
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-Bp973DaS_mjs.js.LICENSE.txt
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js
  js/files_pdfviewer-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-CSmrMOEO_mjs.js.LICENSE.txt
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js
  js/files_pdfviewer-vendors-node_modules_rehype-highlight_index_js.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1203 fix: Open PDF file in "richdocuments" if it is not downloadable
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
Labels: bug, 3. to review

#1205 [stable30] fix: Open PDF file in "richdocuments" if it is not downloadable
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  src/views/PDFView.vue
Labels: bug, 3. to review

#1206 [stable31] Remove custom handling for public share pages with single files
  js/files_pdfviewer-main.js
  js/files_pdfviewer-main.js.map
  js/files_pdfviewer-public.js
  js/files_pdfviewer-public.js.license
  js/files_pdfviewer-public.js.map
  js/files_pdfviewer-public.js.map.license
  lib/AppInfo/Application.php
  lib/Listeners/LoadPublicViewerListener.php
  src/public.js
  src/utils/hideDownload.js
  src/utils/isPdf.js
  src/utils/isPublicPage.js
  src/utils/isSecureViewerAvailable.js
  src/views/PDFView.vue
  webpack.config.js
Labels: bug, 3. to review

#1207 chore: Update GitHub workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: 3. to review

#1214 chore(tests): Cleanup bootstrap.php to be forward-compatible
  tests/bootstrap.php
Labels: 3. to review
